### ISSUE TITLE
Errors when trying to compile using Xcode 10 Swift 4.2

### ISSUE THREAD

**Issue by jayczech23** [icanzilb/SwiftSpinner#132]
I am getting a compilation error when trying to compile my XCode project using:

- Xcode 10
- Swift 4.2
- SwiftSpinner version 1.6.2

Snippets of the code in SwiftSpinner.swift that is giving me the errors are below:

<img width="862" alt="screen shot 2018-12-04 at 9 17 50 pm" src="https://user-images.githubusercontent.com/18233718/49489842-1924be80-f80a-11e8-91b9-79aae80dd8ca.png">
<img width="863" alt="screen shot 2018-12-04 at 9 17 24 pm" src="https://user-images.githubusercontent.com/18233718/49489843-1924be80-f80a-11e8-8a65-a60bcafeabe3.png">
<img width="856" alt="screen shot 2018-12-04 at 9 17 12 pm" src="https://user-images.githubusercontent.com/18233718/49489844-1924be80-f80a-11e8-86be-c5a6248c2c88.png">

**Comment by andreamazz** [comment]
Duplicate of https://github.com/icanzilb/SwiftSpinner/issues/128

> So I found a solution to this problem. The issue arrises if you update all the PODS in your Workspace before converting your source to Swift 4.2. I was using Swift 4 with SwiftSpinner 1.5.0. I updated all my pods before I updated my project source files. Mistake. Once I updated all the source files (and not the pods), then deleted all the existing PODS in the project directory, then ran Pod Install, I got things working with SwiftSpinner 1.6.2

**Comment by jayczech23** [comment]
I'll give that a go thank you @andreamazz
